name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"   # speeds up installs using Poetry's cache

      - name: Install Poetry
        run: pipx install poetry

      - name: Install deps (app + dev)
        run: poetry install --no-interaction --no-ansi

      - name: Lint (Ruff)
        run: poetry run ruff check .

      - name: Format check (Black)
        run: poetry run black --check .

      - name: Import order check (isort)
        run: poetry run isort --check-only .

      - name: Run tests (pytest)
        run: poetry run pytest -q
